### ISSUE TITLE
windows binaries

### ISSUE THREAD

**Issue by mlubin** [JuliaGraphs/GraphViz.jl#12]
Upstream provides windows binaries but seemingly only 32-bit. @tkelman, do you think we could get this into opensuse? Relatively high priority since I'd like to use this package in a tutorial in 4 weeks.

**Comment by tkelman** [comment]
@mlubin are you still hoping to get this to work or do you have a backup plan? I'm making some progress, but don't know yet if I'll get all the way to the dll's you want. Do you have some example code for testing if I do? No package tests here...

**Comment by mlubin** [comment]
I basically have a backup plan to tell Windows users to use JuliaBox if they want to run the parts of the tutorial that need GraphViz. So this isn't a terribly high priority and may not be the best use of your time. But if you feel the need to fix windows build issues (aka gardening) then it would be appreciated. The tutorial is next Monday btw.
The best test I have is to copy and paste the examples from the readme and see if they display correctly inline in IJulia.

**Comment by tkelman** [comment]
I'm distracting myself while at a retreat for the next few days, the other thing I'd be working on is a MathProgBase expression-tree OSiL writer. If you were on IRC right now I'd be bugging you about that, trying to figure out `constr_expr` doing strange things from JuMP.

Monday would be pretty tight for getting things all proper into the upstream openSUSE repo, if I can even get it working all the way.

**Comment by mlubin** [comment]
Greedily an OSiL writer would help out JuMP more than windows binaries for GraphViz, but either way you'd be helping someone :)
Better to open a JuMP issue about ``constr_expr``, I'm also traveling right now.

**Comment by swgregg** [comment]
New user attempting to use Julia for an algorithms class... just seeing if this issue is likely what is keeping me from being able to Pkg.add GraphViz on my windows machine. Trying to create a graph for a class project using Graphs.jl, but not having much luck plotting.

**Comment by mlubin** [comment]
@swgregg, yes, GraphViz.jl won't at all on Windows.

**Comment by smeme** [comment]
Are there plans to resolve `Graphviz` for windows issues? Wonder how `DiagrammeR` for `R` does it? https://github.com/rich-iannone/DiagrammeR.

**Comment by tkelman** [comment]
Still needs work upstream with graphviz itself, I got most of the way there but didn't completely finish last time I hacked at this. How do you read an R package's build/install setup?

**Comment by smeme** [comment]
I am not sure what you mean. On Windows, packages are built using R provided mingw-toolchain as part of Rtools.  Windows packages generally include pre-compiled dlls.

**Comment by tkelman** [comment]
Where do I find the build instructions that get used for that? I don't know R at all, but looking at that package it doesn't appear to actually be calling the graphviz libraries, just reading input / producing outputs using the dot format.

**Comment by smeme** [comment]
OK. Yes, it seems that DiagrammeR simply reads dot file and renders it using `viz.js` (https://github.com/mdaines/viz.js/). `viz.js` which seems to use `enscripten` "an LLVM-to-JavaScript Compiler" to generate java-script from graphviz code. 
Two related project listed on `viz.js` site: 
https://github.com/gyuque/livizjs
https://github.com/bpartridge/graphviz.js

**Comment by musmo** [comment]
Did this ever  get resolved. Was hoping to use GraphViz today but reading this looks like the issue on Windows hasn't been fixed.

**Comment by tkelman** [comment]
Don't think so. They merged a few of my patches (https://github.com/ellson/graphviz) but it wasn't entirely working.

**Comment by davidanthoff** [comment]
I'd also be interested in this :)

**Comment by hpoit** [comment]
BayesNets.jl would also be interested, GraphViz discussed on issue [56](https://github.com/sisl/BayesNets.jl/issues/56)

**Comment by Keno** [comment]
The future is now
