### ISSUE TITLE
renderer for x11 is unavailable

### ISSUE THREAD

**Issue by JohnPSpaw** [JuliaGraphs/GraphViz.jl#18]
I am using GraphViz in Emacs with ESS on OS X Yosemite and am having an issue with rendering my .dot files. Here is my code, which seems to be failing at the final rendering step.

using GraphViz
g = open("graph.dot","r") do io Graph(io) end
GraphViz.layout!(g)
GraphViz.render_x11(GraphViz.Context(),g)

 The package is making it past the layout step, but gives the result "Error: renderer for x11 is unavailable
-1" even though I have X11 on my machine. Is there additional setup that needs to be done? Furthermore, if there is another way to render the graph without X11, I am willing to do that.

**Comment by dehann** [comment]
Hi,

I'm having a similar-ish problem but on Ubuntu 14.04, however the same code works on a 12.04 system. The initial indications are writemime and Cairo.jl related. I filed an issue there:

https://github.com/JuliaLang/Cairo.jl/issues/109

I'm trying to draw a Graphs.jl with GraphViz.jl -- this works fine on 0.3.8, 0.3.10, 0.4-dev+5933 (12.04) but not 0.4-dev+5933 on 14.04.

GraphViz.Graph(to_dot(g))

Error: renderer for julia:cairo is unavailable

MethodError: writemime has no method matching writemime(::Base.Base64.Base64EncodePipe, ::Base.Multimedia.MIME{symbol("image/png")}, ::Void)
Closest candidates are:
writemime(::IO, !Matched::AbstractString, ::Any)
writemime(::IO, !Matched::Base.Multimedia.MIME{symbol("text/plain")}, ::Any)
writemime(::IO, ::Base.Multimedia.MIME{symbol("image/png")}, !Matched::Cairo.CairoSurface)
...

in writemime at /home/dehann/.julia/v0.4/GraphViz/src/GraphViz.jl:590

More info
------------
I'm working from IJulia notebook and there are 5 packages of interest:

    Cairo 0.2.28
    Gadfly 0.3.13
    GraphViz 0.0.4
    Graphs 0.5.5
    IJulia 0.2.5


thanks,
dehann

**Comment by lobingera** [comment]
I've seen this in JuliaLang/Cairo.jl#109
How does it differentiate from #11 ?

**Comment by dehann** [comment]
Hi @lobingera, thanks I did not see #11 issue before -- I think the difference is my issue is happening on Ubuntu 14.04. I'll post there.

**Comment by lobingera** [comment]
any maybe: Graphviz is not available via Pkg.add?

**Comment by Keno** [comment]
The current Graphviz_jll is also not built against x11, but we do build against cairo. I'd prefer to keep it that way and use the generic image viewer API for viewing graph results.
