### ISSUE TITLE
Example Fails: no method matching open(::Type{GraphViz.Graph}, ::String)

### ISSUE THREAD

**Issue by michaellindon** [JuliaGraphs/GraphViz.jl#31]
I ran the example but it fails:

```
julia> using GraphViz

julia> open(Graph,"mygraph.dot")
ERROR: MethodError: no method matching open(::Type{GraphViz.Graph}, ::String)
Closest candidates are:
  open(::AbstractString, ::AbstractString) at iostream.jl:132
  open(::Function, ::Any...) at iostream.jl:150
  open(::Base.AbstractCmd, ::AbstractString) at process.jl:575
  ...
Stacktrace:
 [1] macro expansion at ./REPL.jl:97 [inlined]
 [2] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73

```

I'm using Julia Version 0.6.0 (2017-06-19 13:05 UTC)

**Comment by mantzaris** [comment]
I have tried saving he example with the graph string representation in the 'mygraph.dot' file and put into a variable the 'Graph' object with receiving the same error. 
`open(Graph(""" digraph graphname { a -> b -> c; b -> d; }"""),"mygraph1.dot")
`

**Comment by Keno** [comment]
The API has been updated and now uses either FIleIO or a macro.
